# -*- coding: utf-8 -*-
"""predict.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBgRK4fW0vbOIr8iJLomFu6n5iAEwn2U
"""

import pandas as pd
import joblib

# Load model from local pickle file
model = joblib.load("best_customer_risk_model.pkl")

# Get feature columns from training set (ensure order is same)
FEATURES_PATH = "features_train_woe.csv"
feature_columns = pd.read_csv(FEATURES_PATH).columns.tolist()

def predict_customer_risk(input_df):
    """
    Predict customer risk given an input DataFrame.
    Returns dict with predicted class and risk probability.
    """
    input_df = input_df[feature_columns]  # Enforce column order
    prediction = model.predict(input_df)
    risk_proba = model.predict_proba(input_df)[:, 1]
    return {
        "prediction": prediction.tolist(),
        "risk_probability": risk_proba.tolist()
    }

# Example usage
if __name__ == "__main__":
    sample = pd.DataFrame({
        'Recency_woe': [1.5],
        'Frequency_woe': [-0.8],
        'Monetary_woe': [2.1]
    })
    result = predict_customer_risk(sample)
    print("Prediction Result:", result)